#
# Copyright (c) 2021 the original author or authors.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.setup.deploymentName }}-notebook-jupyter
  namespace: {{ .Values.setup.deploymentName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.setup.deploymentName }}-notebook-jupyter
  template:
    metadata:
      labels:
        app: {{ .Values.setup.deploymentName }}-notebook-jupyter
    spec:
      volumes:
        - name: {{ .Values.setup.deploymentName }}-notebook-data
          persistentVolumeClaim:
            claimName: {{ .Values.setup.deploymentName }}-notebook-pvc
        - name: {{ .Values.setup.deploymentName }}-notebook-work
          persistentVolumeClaim:
            claimName: {{ .Values.setup.deploymentName }}-notebook-work-pvc
      initContainers:
        - name: volume-permissions
          image: busybox
          command: [ 'sh', '-c', 'chmod -R 777 /data' ]
          volumeMounts:
            - name: {{ .Values.setup.deploymentName }}-notebook-data
              mountPath: /data
      containers:
        - name: {{ .Values.setup.deploymentName }}-notebook-jupyter
          image: {{ printf "%s/%s/%s" .Values.setup.repository .Values.setup.imageOwner .Values.setup.deploymentImage }}
          command: [ "start-notebook.sh" ]
          args: [ {{ printf "--NotebookApp.base_url=/notebook/%s" .Values.setup.deploymentName }},
                  --NotebookApp.ip=0.0.0.0,
                  --NotebookApp.allow_remote_access=True ]
          env:
            - name: "PASSWORD"
              value: {{ print .Values.setup.jovyanPassword | default "2rup5k83bsHwvBUc" }}
          volumeMounts:
            - name: {{ .Values.setup.deploymentName }}-notebook-data
              mountPath: /home/jovyan/data
            - name: {{ .Values.setup.deploymentName }}-notebook-work
              mountPath: /home/jovyan/work
          ports:
            - containerPort: 8888
          resources:
            limits:
              nvidia.com/gpu: {{ .Values.setup.numberOfGpus | default "1" }} # requesting 1 GPU
              cpu: {{ .Values.setup.notebookCpuLimit | default "1000m" | quote }}
              memory: {{ .Values.setup.notebookMemoryLimit | default "5Gi" | quote }}
              ephemeral-storage: "100Gi"
