#
# Copyright (c) 2021 the original author or authors.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
#

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.setup.deploymentName }}-notebook-pvc
  namespace: {{ .Values.setup.deploymentName }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aist-hostpath
  resources:
    requests:
      storage: {{ .Values.setup.storageVolume | default "10Gi" | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.setup.deploymentName }}-notebook-work-pvc
  namespace: {{ .Values.setup.deploymentName }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aist-hostpath
  resources:
    requests:
      storage: "100Gi"
